language: node_js
node_js: 
  - 10.15.1
cache:
  directories:
    - "node_modules"
script:
  - npm run test

after_success: npm run coverage
addons:
    code_climate:
        repo_token: dhgfkgfjhgkfgdsr676483749284ugrygstdkatdyaskfudtwavawtesgdyacSHVMJVSDASZGFVAS,DJFS
script: istanbul cover npm run test -- -R spec
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
