language: node_js
node_js:
- 10.15.1
cache:
  directories:
  - node_modules
script:
- npm run test
after_success: npm run coverage
env:
  matrix:
    secure: FrLr2a+N6IBfaADYZuO4JbNz5LIynUL9f4akR4yTkvYtLxGMyV/dc0mc64XD4C+Dc9tSOETwKgvEkXlde2exG7CY53iskeezjSDAUvMywOmthOB2JSlixe+Kzp05XSuHMA0giNtUb/USKKptjVCcNapGMyUF125U36UWxzm2RC+wvTD7rLsRb6QlhsbHUrnAKYV3pjEU9j6N5oS7nLQ4agffaNW+Iu8zl2YEeAewhoCsTPSL4FLTKkmYO5qIrnp/9RPdeB6XvSPohwxbnc+OgWORRLGK0e/vu3Yq99gEw+lmmmKM2QjkhpIov7sT/R9QeoRZJTspeobntrVUuw8t6EpjW9JTn9oy8BQcSF9LaprF4rHMw1ujyfi1TAaqBjKYqk6FeclJRxnjmWj5TrqjWUPgCrrnojg1tof143lT5KqIo6efkgQlEbmGNK1IsL0oTLQW/ZcVYCB6ycWUyOZy+HWf0CAlUB0LvIGLsuvnFxSPysUkRTwzGg185Bh7miD646L6oTRTpjy745zFCG+SK+UUzmSd0Qt9GFcljP998vMI8izMfF3mK2cy4rIqlVjunOPskpcNKGLEuXCkXASCGnH+EXiuNH5SCW850MNqSJ2vl+g7yGEh2s3gZvtq6lYeS6BmefOqc1u6KDBrXuYJdNiUXdM6hFPuvKGdHK55Jc8=
